### ISSUE TITLE
Publish the guide

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/heron#100]
Even if it is too small and far from complete, "some" documentation is better than "none".

Let's publish the guide.

**Comment by JoeHowarth** [comment]
Hey @jcornaz, not sure what you meant by "publish", but the md guide in the repo tries to embed code but github doesn't support that markdown syntax. Perhaps consider using https://github.com/zakhenry/embedme to keep the examples in-sync and compile-checked while allowing users to easily read the source code and guide inline. 

....Or maybe it's easier to just publish the gitbook, not sure what that takes :) 

Thanks for your work!

**Comment by jcornaz** [comment]
Thanks for the suggestion. I'll have a look at embedme.

in my post "publishing" meant simply building the mdbook and pushing to GitHub pages. Wich isn't much work at all.

But, to be honest I am not fully sure what is the best way forward. I kinda feel that it would be possible (and nice) to solely rely on docs.rs, and just add more "guide level" documentation in there. It would be quite nice because very discoverable and well integrates with the "reference level" documentation.

**Comment by jcornaz** [comment]
I decided to use solely docs.rs for all documentation (guide and reference). It is therefore already published, and I won't publish a separate "book" or guide.

I removed the sources of the guide in 010a773e6a64fad1bfefc0df0b28537f95a2e3f4. Most of it was already more or less explained in the rust docs. That documentation can of course be improved. I am open to suggestions and contributions.
