### ISSUE TITLE
Execute physics step in-sync with the bevy update

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/heron#107]
## The problem

In a game the time between each frame may vary significantly from frame to frame. The physics simulation should not suffer from that. Its progression should always be at the same "speed" of the real world time (eventually scaled by a user-defined factor).

It is also important to garantee a maximum "delta-time" between each physics step to prevent objects passing through each others at lower frame rate.

For these reasons, the physics step runs at a fixed time-step which makes it out-of-sync of the main frame update. That means the physics step may be executed: 0, 1 or n times during a single bevy update.

But this adds complexity for both usage and design/maintenance of the library:

* The user has to know and use correctly `add_physics_system`
* It isn't possible (ATM) to easily deal with bevy states (see #81)

And it also has a performance cost because it requires a dedicated bevy stage which introduces thread synchronization points and prevent other (non-physics related) systems to run in parallel of the physics.

## A potential solution

The most problematic part is that there can be multiple physics step during a single bevy update.

But instead of using the bevy built-in `FixedTimeStep` there could be a different run criteria to make sure that at each bevy update the physics step runs either exactly once OR doesn't run. But it would never run the physics step multiple times in a single bevy update.

In other words:
* If the frame rate is higher than the defined physics step rate: The physics step is not executed every frame. (To preserve the defined physics step rate)
* If the frame rate is lower than the defined physics step rate: The physics step is executed exactly once at each frame. That means the physics simulation will slows down.

Then the physics system could run in the `CoreStage::PostUpdate` stage and provide labels to allow running user-systems before or after the physics step.

## Pros

* No need for `add_physics_system`. The user can read and mutate the physics component normally
  * The physics system will catch up when they'll run (Since bevy 0.5, changes can be detected even if they didn't occur during the same frame)
* Support for bevy state systems comes for free (see #81)
* Simpler design and developement
* Some may like that physics simulation slows down in case of low FPS, as it make the game more "fair"
* Potential performance gain as the physics can run in parallel of others systems defined by the user, bevy or other plugins.
* Better performance in case of low FPS as the physics step runs only once per update (instead of multiple times per frame)

## Cons

* Some may NOT like that physics simulation slows down in case of low FPS

I think the first point is fine. We cannot please everyone. Some will like that physics simulation slow downs in case of low FPS. And some will not like it. Heron doesn't aim to be a drop-in replacement for rapier and bevy_rapier. It aims to makes things easier for people who do not need advanced physics control. If someone needs a more advanced/different handling of the physics in case of low FPS, they can use rapier/bevy_rapier.

**Comment by yaymalaga** [comment]
In general I really like the plan! 

Regarding the FPS, it would be interesting to see if it is possible to apply/change a `with_run_criteria(FixedTimestep::step(X))` in a SystemSet dynamically. Ideally, we should be able to optionally use a function (like in the time scale PR) to set a min/max fps for the physics. That way, the cons would just disappear.

Maybe it's interesting to create an issue in Bevy to discuss if this is feasible.

**Comment by jcornaz** [comment]
Update: After playing around I found that rapier doesn't like having `IntegrationParameters::dt` being update every single frame. That made me rethink about this problem and I made a new iteration to improve the design of the solution (still going in the same direction).

I updated the initial comment of the isse to reflect the current status of the design.

In short here is the main change is:

> * If the frame rate is higher than the defined physics step rate: The physics step is not executed every frame. (To preserve the defined physics step rate)
> * If the frame rate is lower than the defined physics step rate: The physics step is executed exactly once at each frame. That means the physics simulation will slows down.
