### ISSUE TITLE
Docs.rs page empty

### ISSUE THREAD

**Issue by esposm03** [jcornaz/heron#126]
It seems that [no documentation](https://docs.rs/heron/0.9.0/heron) was generated by docs.rs for heron 0.9.0, although the build did not fail ([here's the log](https://docs.rs/crate/heron/0.9.0/builds/405610), although it doesn't seem useful)

**Comment by jcornaz** [comment]
Thanks for the report.

That's odd, I don't know what can cause that :-/

I'll investiguate.

**Comment by jcornaz** [comment]
@zicklag, I did a quick git-bisect, and it looks like the documentation has disapeared at 6e0ae98fc35c0d8012fc2301cea9accc81c71123. Do you think it can be a side-effect of the `cfg_aliases`?

**Comment by jcornaz** [comment]
Ah, I know what happend. It's because there is no more feature enabled by default, and without choosing explictly either `2d` or `3d` the `heron` crate is actually empty.

I have to tell rust to build the documentation using all features. I'll publish a fix today.

**Comment by jcornaz** [comment]
The documentation is back on docs.rs: https://docs.rs/heron/0.9.1/heron/

**Comment by esposm03** [comment]
Thank you for the quick fix!
