### ISSUE TITLE
Dynamic body partially trespassing another

### ISSUE THREAD

**Issue by nickfla1** [jcornaz/heron#135]
## Description

I'm experiencing some issues with dynamics bodies falling onto another body, like in a character jumping (see example below).

The PhysicsStep is set to `MaxDeltaTime` and it's configured as follows:

```rs
.insert_resource(PhysicsSteps::from_max_delta_time(Duration::from_secs_f32(
  1.0 / 60.0,
)))
```

The entity itself, instead, is configured as such:

```rs
let size = Vec2::new(16.0, 34.0);

commands
  .insert(CollisionShape::Cuboid {
    half_extends: size.extend(0.0) / 2.0,
    border_radius: None,
  }),
  .insert(CollisionLayers::none()
    .with_group(PhysicsLayer::Player)
    .with_mask(PhysicsLayer::World),
  })
  // ... And other components
```

Also, I cap the negative velocity to `-400.0`.

Feel free to ask any other needed information.

## Example

https://user-images.githubusercontent.com/85181513/129248867-b6bd2da1-8bc7-4b8c-92cc-6e30003ba4e3.mov

As you can see, it sometimes goes through the floor.

**Comment by zicklag** [comment]
I've run into the same thing with my game. I've almost gotten rid of it by tweaking the integration parameters, but not completely:

https://github.com/katharostech/skipngo/blob/f27d38f73091784c8480966362f3ec46b1961cfd/src/plugins/game/systems/game_init.rs#L34-L41

You should be able to get it working much better than that by tweaking those parameters, but I'm not 100% sure exactly how to get rid of it completely yet.

I'm going to be looking deeper into this when I get the chance and I'll try to remember to come back and comment here if I do. Feel free to ping me if I don't reply sometime within the next month.

Also, this is technically a rapier issue not a heron issue if I understand correctly.

**Comment by jcornaz** [comment]
> Also, this is technically a rapier issue not a heron issue if I understand correctly.

Yes most likely. Heron is only the api. The simulation is done by rapier.

Maybe you can try using enabling rapier's CCD solver (never tried it personally). And ofc, twicking the integration parameter (resource: `rapier2d::dynamics::IntegrationParameters`)

But I don't think there is much heron can do directly. Unless you find that you don't have the probem when using `bevy_rapier` or directly `rapier`.

**Comment by nickfla1** [comment]
I confirm that's happening with `rapier` as well. 
I'll close the issue since it's not relevant to this repository and I'll probably use another method for collision handling. 

Thank you!
