### ISSUE TITLE
Fix collision_shapes_in_child_entity.rs

### ISSUE THREAD

**Issue by vihdutta** [jcornaz/heron#172]
When I run examples/collision_shapes_in_child_entity.rs the build just shows a blank screen although I do not get any warnings or syntax errors.

**Comment by jcornaz** [comment]
Hi, thanks for the report.

I just tried again today, and it seems to work as far as I can see.

Can you provide more context? Operating system, rust version, rendering backend (x11 or vulkan), anything you can think of.

Do the other example work?

**Comment by vihdutta** [comment]
I apologize for the lack of information in the post above. Oddly enough, when I tried it again it started working. I'll let you know with more details if it comes up again.
