### ISSUE TITLE
SmallVec leaked into the public API

### ISSUE THREAD

**Issue by Shatur** [jcornaz/heron#206]
`SmallVec` currently used in [CollisionData::new](https://docs.rs/heron/latest/heron/struct.CollisionData.html) which is public. I would like to suggest to re-export `SmallVec` for convenience.

**Comment by jcornaz** [comment]
Oups, that's a mistake. I'd rather depreciate that member, rather than re-exporting small ex though. 

I have to look at it, thanks for the report.

**Comment by Shatur** [comment]
Do you want to remove this member completely?

**Comment by jcornaz** [comment]
> Do you want to remove this member completely or the whole `CollisionData`?

Only the constructor. I am bothered by having smallvec being part of the public API. That was the mistake. The rest of `CollisionData` is fine AFAIK. I have to see how exactly I move forward (I cannot simply remove it, that would be a breaking change). But I will address that as soon as I find time.

**Comment by jcornaz** [comment]
I solved it by generalizing the argument to `impl IntoIterator<Item=Vec2>`. So one can pass any collection type, and even iterators.
