### ISSUE TITLE
Add more constructors to CollisionLayers

### ISSUE THREAD

**Issue by Shatur** [jcornaz/heron#209]
We currently have [CollisionLayers::all](https://docs.rs/heron/2.0.1/heron/struct.CollisionLayers.html#method.all) and [CollisionLayers::none](https://docs.rs/heron/2.0.1/heron/struct.CollisionLayers.html#method.none). But this methods will initialize both masks and groups.
For a common case, where I would like to define a layer with single group I have to write the following:

```rust
CollisionLayers::from_bits(
    CollisionLayer::Character.to_bits(),
    CollisionLayer::all_bits(),
)
```

I would suggest to add 2 additional helpers: `all_groups`, `all_masks`. In this case the example above will look in the following way:

```rust
CollisionLayers::all_masks().with_group(CollisionLayer::Character);
```

**Comment by jcornaz** [comment]
Ah, interesting. Never needed that personally, but I have nothing against it. It is up-for grab ;-)
