### ISSUE TITLE
Add `intersections_with_shape` method from rapier

### ISSUE THREAD

**Issue by ShadowCurse** [jcornaz/heron#218]
During the Bevy Jam we needed `intersections_with_shape` functionality from rapier, but it was unavailable, so we made a quick hack to add it. 
Now i have made a proper implementation and want to share it.

**Comment by ShadowCurse** [comment]
I was implementing a pulsing mechanic and the main idea was that some object (for example explosive barrel) will have a zone attached to it and it will "pulse" periodically (or once). And instead of checking collision events and record entities that are near the object I thought of using `intersections_with_shape` to get get all entities in the area at once.

**Comment by jcornaz** [comment]
Ah, interesting. Thanks for sharing.

I am wondering, what if #216 was available? I guess that, with that feature, you could make the barrel a sensor. And instead of reacting on collision event as they happen, simply grab the list of collided entities from the `CollisionEntities` component at each pulse?

Would that work? Would it be better or less good?

**Comment by ShadowCurse** [comment]
hmm..  I think that would have worked for our case. Definitely would be a bit less code. But i can think of one example, where `intersections` are better: if we need to check the layers for possible interactions, like a fire area should not interact with walls but should interact with player and enemies.

**Comment by jcornaz** [comment]
>  if we need to check the layers for possible interactions, like a fire area should not interact with walls but should interact with player and enemies.

The `CollisionEntities` component contains only entities that are collided according to the defined layers. So if the fire area is configured to collide with players only, then the `CollisionEntities` will contain player entities, not walls.

And even for potentially more complex cases (that I don't even visualize yet), because we anyway need to query the referenced entities, we can simply use query filters.

example:

```rust
fn pulse_fire_aoe(
  mut players: Query<&mut Health, With<Player>>,
  mut fire: Query<(&mut Timer, &CollitionEntities), FireArea>,
  time: Res<Time>,
) {  
  for (mut timer, collisions) in fire.iter_mut() {
    timer.tick(time.delta());
    if timer.finished() {
      for entitiy in collisions.collided_entities() {
        if let Ok(mut health) = players.get_mut(entity) {
          health.0 -= 10;
        }
      }
    }
  }
}
```

Would `intersections_with_shape` make it simpler? And if yes, how?

**Comment by ShadowCurse** [comment]
Ok, for some reason i thought that `CollisionEntities` will contain all entities in the area, my bad.
Then `intersections_with_shape` seems kinda useless for this use case, unless the area is created and checked in one frame, so there are no colliders to take intersecting entities from. But right now I can not think of a game mechanic that needs this.
Also `intersections_with_shape` might be easier to use, because you don't need to keep the sensor area around and manage it.
Also as I remember if a new sensor is created in place, where there are other colliders already exists, then there would be no collision events, until these colliders go out of the area and enter it again.

**Comment by jcornaz** [comment]
> Also `intersections_with_shape` might be easier to use, because you don't need to keep the sensor area around and manage it.

Keeping a sensor area seems quite cheap and easy to me. And I feel like we'd anyway some way to keep track of where the detection area should be.

Anyway, that's too theoric to lead anywhere IMO. Better wait until someone actually has a use-case to share.

> Also as I remember if a new sensor is created in place, where there are other colliders already exists, then there would be no collision events, until these colliders go out of the area and enter it again.

That would be annoying indeed. But I that's the case, then we may instead try to fix that problem directly.

> Then `intersections_with_shape` seems kinda useless for this use case, unless the area is created and checked in one frame, so there are no colliders to take intersecting entities from. But right now I can not think of a game mechanic that needs this.

Okay, thanks for the feedback. Then I think I close this issue as "wontfix". If someone bumps into a use-case that would be better solved with `intersections_with_shape` then we can re-open this issue and re-consider it.

Thanks for sharing ;-)
