### ISSUE TITLE
Re-enable debug-3d since bevy_debug_lines implemented bevy 0.7 support

### ISSUE THREAD

**Issue by papricasix** [jcornaz/heron#260]
Hi, it should be possible now to re-enable the debug-3d feature:
https://github.com/Toqozz/bevy_debug_lines/commits/master

#244

**Comment by jcornaz** [comment]
Being up-to-date in the main branch is not enough. In order to use it in heron, it must be published on crates.io.

**Comment by papricasix** [comment]
Finally there has been a new release with bevy 0.7 support: https://crates.io/crates/bevy_prototype_debug_lines/versions
