### ISSUE TITLE
Position/Rotation offset for collision shape 

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/heron#31]
As a user, I would like to have an offset for the collision shape (relative to its entity `GlobalTransform`), so that I don't need to use parent-child hierarchy (with shape being parent) when the origin and orientation of the colision shape doesn't match the origin/orientation of my sprite/mesh.

There could be a `BodyOffset { translate: Vec3, rotate: Quat }` component.

**Comment by jcornaz** [comment]
After some experiments and thinking I decided to come up with a design that would solve both this issue and the ability to have multiple collision shapes for a single rigid body (#11):

First, `Body` would be renamed to `CollisionShape` and `BodyType` to `RigidBody`.

A `CollisionShape` would declare the collision shape only. That collision shape would be attached to the first `RigidBody` found in
1. The same entity
2. The ancestors of the entity (first, the parent, then the parent of the parent, etc.)

If no `RigidBody` is found in either the entity or its ancestors, then everything behaves like if the entity containing the `CollisionShape` also had a `RigidBody::Dynamic` component.

### Examples

A simple dynamic body:

```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(CollisionShape::Sphere { .. });
```

A simple non-dynamic body:
```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(RigidBody::Static)
  .insert(CollisionShape::Sphere { .. };
```

Offset for the collision shape:
```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(RigidBody::Dynamic)
  .with_children(|children| {
    children.spawn_bundle(CollisionShapeBundle {
          shape: CollisionShape::Sphere { .. },
          transform: Transform { .. }, // <-- The offset,
          ..Default::default()
    });
  });
```

Multiple collision shapes for the same body:
```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(RigidBody::Dynamic)
  .with_children(|children| {
    children.spawn_bundle(CollisionShapeBundle {
          shape: CollisionShape::Sphere { .. },
          transform: Transform { .. }, // <-- Relative position of the first shape,
          ..Default::default()
    });
    children.spawn_bundle(CollisionShapeBundle {
          shape: CollisionShape::Cuboid { .. },
          transform: Transform { .. }, // <-- Relative position of the second shape,
          ..Default::default()
    });
  });
```

**Comment by yaymalaga** [comment]
Another useful feature is the ability to add different *sensor collisions* to the same entity as children. Right now, *Sensor* is a body type, so I don't know if you would be able to add it as a child and then add to it some children collisions (it doesn't seem to be really ergonomics anyway).

**Comment by jcornaz** [comment]
A small iteration on my design above. I will prbably make the `RigidBody` component mandatory (And not longer consider the entity as being a dynamic rigid body if the component is not found).

I found out that having `RigidBody` being an optional component quickly complicates things with this new design. Especially when it comes to handling body/shape removal. And I'm afraid that with this new design, if the `RigidBody` component is optional, it can lead to some surprising behaviors for the users.

Otherwise to answer you @yaymalaga:

> Another useful feature is the ability to add different sensor collisions to the same entity as children. Right now, Sensor is a body type, so I don't know if you would be able to include it as a child and then add to it some children collisions (it doesn't seem to be really ergonomic anyway).

With this design it would be possible to create a sensor with multiple collision shapes.

```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(RigidBody::Sensor) // <-- Make it a sensor
  .with_children(|children| {
    children.spawn_bundle(CollisionShapeBundle {
          shape: CollisionShape::Sphere { .. },
          transform: Transform { .. },
          ..Default::default()
    });
    children.spawn_bundle(CollisionShapeBundle {
          shape: CollisionShape::Cuboid { .. },
          transform: Transform { .. },
          ..Default::default()
    });
  });
```

If you want to have both sensor AND a physics body, then you'd have to create both a rigid body AND a sensor. Like this:

```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(RigidBody::Dynamic) // <-- The rigid bdoy
  .with_children(|children| {
    children.spawn_bundle(CollisionShapeBundle { .. }); // <-- The *physics* collision shape

    children.spawn((
        RigidBody::Sensor, // <-- The sensor
        CollisionShape::Sphere { .. }, // <-- The *sensor* collision shape
        Transfrom { .. },
        GlobalTransform::default()
    ));
  });
```


I know this design is different from what rapiers does, as rapier put the "sensor" flag on the shape rather than the rigid body. But I personally find this design not-intuitive and I prefer the way Unit/Godot handle it: First, chose between rigid body/sensor, and the attach collision shapes.

**Comment by jcornaz** [comment]
@yaymalaga, yes it woud be possible to replicate this code using my implementation. Here is how it would be:

```rust
commands.spawn_bundle(SpriteBundle { .. })
  .insert(RigidBody::Dynamic)
  .with_children(|children| {
    children.spawn_bundle(CollisionShapeBundle { // <-- One *physics* collision shape
          shape: CollisionShape::Sphere { .. },
          transform: Transform { .. },
          ..Default::default()
    });
    children.spawn_bundle(CollisionShapeBundle { // <-- Another *physics* collision shape
          shape: CollisionShape::Cuboid { .. },
          transform: Transform { .. },
          ..Default::default()
    });
 
    children.spawn(RigidBody::Sensor)
       .with_children(|sensor_children| {
             sensor_children.spawn_bundle(CollisionShapeBundle { // <-- One *sensor* collision shape
                  shape: CollisionShape::Sphere { .. },
                  transform: Transform { .. },
                  ..Default::default()
            });
            sensor_children.spawn_bundle(CollisionShapeBundle { // <-- Another *sensor* collision shape
                  shape: CollisionShape::Cuboid { .. },
                  transform: Transform { .. },
                  ..Default::default()
            });
       });
  });
```

That being said, I actually aggree that it would be more ergonomic to define a "sensor" flag on the collision shape. I created a separated issue for it: #98
