### ISSUE TITLE
Allow to apply force/acceleration to a rigid body

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/heron#44]

**Comment by ryo33** [comment]
How about renaming the `Velocity` to `Movement` and adding the following APIs:
- `from_velocity(Vec3)`
- `set_velocity(&mut Self, Vec3)`
- `from_force(Vec3)`
- `set_force(&mut Self, Vec3)`
- `apply_force(&mut Self, Vec3)`, `apply_force_at_point`, `apply_impulse`, `apply_impulse_at`, `apply_torque`, `apply_torque_impulse`
- etc.

I think `Velocity` could be an enum. I'm going to create a PR as soon as possible.

**Comment by jcornaz** [comment]
Thanks @ryo33 for the proposition.

That's interesting. But I think one may want to have both a `Force` and a `Velocity`. Maybe he/she wants to *apply* a force and *read* the velocity updated by rapier.

I don't think force and velocities are mutually exclusive. At any point in time an object may have both a velocity and a force being applied.

**Comment by ryo33** [comment]
@jcornaz Thanks!

> Maybe he/she wants to apply a force and read the velocity updated by rapier.

> At any point in time an object may have both a velocity and a force being applied.

I had not thought about that. Yes, it should not be an enum.

**Comment by ryo33** [comment]
@jcornaz 
What do you think about the following APIs?

- Add structs; `Acceleration`, `Impulse`, and `Force`, which has the same fields and similar APIs with `Velocity`.
- On "heron-pre-step": after updating rigid-body with `Velocity`, apply `Acceleration`, `Impulse`, and `Force`.
- On "heron-post-step": with updating `Velocity`, reset `Acceleration`, `Impulse`, and `Force` with `Vec3::zero`.

**Comment by jcornaz** [comment]
Thanks @ryo33 for your considerations. Here are my thoughts so far:

### Acceleration and Force

Accelerations and forces define a change of velocity over time. And one can be describe with the other (when knowing the mass): `Force = mass * acceleration`.

So from that respect, we may consider the force and acceleration to be mutual exclusive and have them being variants of an enum. Maybe the enum name could be `VelocityChange`?

I would, however not reset either the force nor the acceleration. I would let the force/acceleration being applied until the user decide to mutate or remove the component.

### Impulse

An impulse in physics simulation will be a instantanous change of velocity that consider the mass of the object. I see many options to model it (including the one you proposed @ryo33), and I'm not yet sure which one is the best.

But to be honest, I'm starting to think I made a mistake to name thi issue "allow to apply force/impulse". And maybe we should defer the "impulse" feature to later.

Often (if not always) in video game one will change the velocity by simply mutating the velocity. The need to use "impulse" rather that directly mutating the `Velocity` is probably not that strong. And maybe to design a good API for applying impulse, it is better to wait for an actual use-case.

So I think I would like to remove "allow to imply impulse" from the scope of this issue.

**Comment by ryo33** [comment]
@jcornaz 
Thank you for your response. Here is my opinions about it.

## Force and Impulse

> So I think I would like to remove "allow to imply impulse" from the scope of this issue.

I think the impulse is not special against the force. In my opinion, we have mainly four types of velocity changes in gamedev, and I think it's ergonomic if they have consistent or unified APIs.
| type | mass | dt | use-case 1 | use-case 2 |
| --- | --- | --- | --- | --- |
| mutating the Velocity | ignores | ignores | walk | jump the same height regardless of bodyweight |
| Impulse | considers | ignores | jump | throw something |
| Acceleration | ignores | considers | nitro boost | gradually increase velocity regardless of mass |
| Force | considers | considers | push something | wind effects |

Unity has the unified API called [addForce](https://docs.unity3d.com/ScriptReference/Rigidbody.AddForce.html), which accepts velocity change, impulse, acceleration, and force.
Unreal has separate function, [addForce](https://docs.unrealengine.com/en-US/API/Runtime/Engine/Components/UPrimitiveComponent/AddForce/index.html) and [addImpulse](https://docs.unrealengine.com/en-US/API/Runtime/Engine/Components/UPrimitiveComponent/AddImpulse/index.html) that have consistent API.

## Mutual exclusive or not
> So from that respect, we may consider the force and acceleration to be mutual exclusive and have them being variants of an enum.

When the first discussion, I noticed that velocity change, force, acceleration, and impulse could be coexistent in the same entity at the same time. For example:

- a force which an enemy moves the player with telekinesis.
- a force of a wind hitting to the player.
- a velocity change from player's left or right input.
- an impulse from player's jump input.

## Resetting force on every step
> I would, however not reset either the force nor the acceleration. I would let the force/acceleration being applied until the user decide to mutate or remove the component.

I prefer `applyForce` style (reset force after every step) to `setForce` style (constant force) in gamedev. I'd like to use `Constant<Force>` to apply a constant force.
With `applyForce` style, it is easy to use `Force` and other components from multiple systems like the following example:

### With resetting

```rust
fn wind_system(...) {
  ...
  let wind: Force = Force::from_linear(Vec3::new(1.0, 0.0, 0.0));

  for (force, state) in velocity_query.iter_mut() {
    if (state.wind_brows()) {
      force += wind;
    }
  }
  ...
}

fn push_system(...) {
  ...
  let push: Force = Force::from_linear(Vec3::new(0.0, 0.0, 1.0));

  for (entity, force) in velocity_query.iter_mut() {
    if (is_pushing(entity)) {
      force += push;
    }
  }
  ...
}
```

### Without resetting

```rust
fn wind_system(...) {
  ...
  let wind: Force = Force::from_linear(Vec3::new(1.0, 0.0, 0.0));

  for (current, prev, force) in velocity_query.iter_mut() {
    if (current.wind_brows() && !prev.wind_brows()) {
      // Wind happens
      force += wind;
    } (!current.wind_brows() && prev.wind_brows()) {
      // Wind goes down
      force -= wind;
    }
  }
  ...
}

fn push_system(...) {
  ...
}
...
```

**Comment by jcornaz** [comment]
> When the first discussion, I noticed that velocity change, force, acceleration, and impulse could be coexistent in the same entity at the same time. 

Yes you're right. Structs it is.

> I prefer `applyForce` style (reset force after every step) to `setForce` style (constant force) in gamedev. I'd like to use `Constant<Force>` to apply a constant force.
> With `applyForce` style, it is easy to use `Force` and other components from multiple systems like the following example:

Yes, definitely. That's an excellent point, thanks for mentionning it.

I may eventually argue that it is a bit "less data-oriented" because forces always have to be redefined by systems, instead of mutating the data only when it changes. Taking your example of "push + wind", I think a data-oriented phylosphy would lead me to introduce a `Push` and `Wind` game compnents to my game. Then I would write a `update_force_system` like this:

```rust
fn force_update_system(mut query: Query<(&mut Force, &Push, &Wind), (Mutated<Push>, Mutated<Wind>)>) {
  for (force, push, wind) in query.iter_mut() {
   *force = push + wind
  }
}
```

It might be less intuitive when comming from Unreal or Unity, but it somehow feel more intuitive to me when I am thinking in a data-oriented paradigm. And it also has some interesting performance properties, because the force is recomputed only when necessary.

Nevertheless, I do think you made a very good point, and resetting the force/velocity can indeed be a valid approach. I have to think more about that.

> I think the impulse is not special against the force. In my opinion, we have mainly four types of velocity changes in gamedev, and I think it's ergonomic if they have consistent or unified APIs.

Yes I aggree that, when providing an impulse API, it has to be unified with the other ways of changing the velocity.

But let's look at the first row of your table: The direct change of velocity. Should we have a component for that? I personally don't think so. I think it is simple and natural enough to mutate the velocity directly: `velocity.linear += delta_v`. And introducing an `Impulse` component would then make create 2 very different API for immediate changes of velocity.

And about the use-cases for impulse, I would personally directly mutate the velocity to jump or throw an object. And even if I wanted to have a more complex a "throw" system that consider the weight of the object being thrown, I wouldn't need any fancy feature from the physics API. I could do: `velocity.linear += impulse / mass`.

Anyway, I don't say I don't want to support impulse. Nor that its API should be different that the other ways of changing the velocity. I only say, I want to focus on force/acceleration for now.

**Comment by ryo33** [comment]
> It might be less intuitive when comming from Unreal or Unity, but it somehow feel more intuitive to me when I am thinking in a data-oriented paradigm. And it also has some interesting performance properties, because the force is recomputed only when necessary.
>
> Nevertheless, I do think you made a very good point, and resetting the force/velocity can indeed be a valid approach. I have to think more about that.

Thank you for your considering. Your data-oriented approach seems good to me, and personally, I'd like to try it in my game project first.

> But let's look at the first row of your table: The direct change of velocity. Should we have a component for that? I personally don't think so. I think it is simple and natural enough to mutate the velocity directly: velocity.linear += delta_v. And introducing an Impulse component would then introduce 2 very different ways to immediatly change the velocity.

> Anyway, I don't say I don't want to support impulse. Nor that its API should be different that the other ways of changing the velocity. I only say, I want to focus on force/acceleration for now.

I understand the point you said. Now I think we don't need `Impulse` component.

## My conclusion for now

Though I suggest the four components, I think all we need is `Acceleration` (without resetting).

As you said;

> Accelerations and forces define a change of velocity over time. And one can be describe one with the other (when knowing the mass): Force = mass * acceleration.

force and acceleration is mutually convertible with mass same as the the relation between velocity change and impulse.

Also, it's intuitive and less redundant that an entity has `Velocity` and `Acceleration`.

**Comment by jcornaz** [comment]
I aggree with your current conclusion. Let's add an `Acceleration` component (without resetting). We'll play with it and iterate on the API if necessary. Thanks @ryo33.

**Comment by ryo33** [comment]
Thanks @jcornaz!!!!
I'm going to create a PR asap!

**Comment by faassen** [comment]
Hey @ryo33 if you happen to be working on this PR in the new few days, I'm interested in collaborating (or at least watching you do it and learn). I sent you a friend request on Discord.

**Comment by ryo33** [comment]
@faassen 
I approved on discord! It's almost done and I'll send a PR later (probably in 6 hours) with some tweaking. Questions, comments and suggestions are welcome!

**Comment by ryo33** [comment]
I create a PR. However, it does not pass tests in 2d yet.
