### ISSUE TITLE
Update to Bevy 0.5

### ISSUE THREAD

**Issue by ValorZard** [jcornaz/heron#79]
Pretty self explanatory. I think it would be nice if you could also update to the latest version of rapier while you're at it, if its possible.

**Comment by jcornaz** [comment]
Yes, ofc.

Migration to bevy 0.5 is already in progress (#78). But we'll have to wait for the upstream library to be updated [bevy_prototype_lyon](https://github.com/Nilirad/bevy_prototype_lyon)

Rapier is already up-to-date in the main branch (not released).

**Comment by yaymalaga** [comment]
The new bevy_prototype_lyon update is now released!

**Comment by yaymalaga** [comment]
Just out of curiosity, is there any plan to support Bevy's new States V2?

As the release notes show, we can now add systems to run on the lifecycles of custom states:
```rust
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
enum AppState {
    Menu,
    InGame,
}

fn main() {
    App::build()
        .add_state(AppState::Menu)
        .add_system_set(SystemSet::on_enter(AppState::Menu).with_system(setup_menu.system()))
        .add_system_set(SystemSet::on_update(AppState::Menu).with_system(menu_logic.system()))
        .add_system_set(
            SystemSet::on_update(AppState::InGame)
                .with_system(game_logic.system())
        )
        .run();
}
```

Ideally, we should be able to run the physics systems just on `AppState::InGame`, instead of using `.add_physics_system()`:
```rust
fn main() {
    App::build()
        .add_system_set(
            SystemSet::on_update(AppState::InGame)
                .with_system(game_logic.system())
                .with_physics_system(game_physics_logic.system())
        )
        .run();
}
```

**Comment by jcornaz** [comment]
This wasn't planned until now. But that's sound like a good idea, so please create a separate issue for this.
