### ISSUE TITLE
Allow to change physics time scale

### ISSUE THREAD

**Issue by yaymalaga** [jcornaz/heron#85]
Following the issue https://github.com/jcornaz/heron/issues/81, that feature would allow us to run the defined physics_systems only on specific States. However, the physics engine itself will continue to be called.

A common feature for games is the ability to pause it at any time. In order to achieve that, we would need to be able to manually choose in which States the physics step will run. 

Another option is exposing a resource for allowing the user to start/stop the physics from any system. For this last option, it could be cool to also allow the user to modify the step used and how often it's called (i.e running the game in slow-motion while in pause to hurry up the player!).

**Comment by jcornaz** [comment]
Yes, that's definitely something I wanted to introduce.

Atm my idea of the API would be something like:

```rust
fn my_system(mut physics_control: ResMut<PhysicsControl>) {
  physics_control.time_scale = 0.5 // slow-motion
  physics_control.time_scale = 1.0 // normal
  physics_control.time_scale = 2.0 // faster
  physics_control.pause() // equivalent to `physics_control.time_scale = 0.0`
  physics_control.resume() // restore previous time scale
}
```

**Comment by yaymalaga** [comment]
I will also take a look to this one, already testing some things locally 😃
